### ISSUE TITLE
[Data preparation]How to use Monocle result Files in TraSig

### ISSUE THREAD

**Issue by DXXDR** [doraadong/TraSig#1]
It's great for TraSig to use track results to infer cell-cell interactions👍. I saw in your paper that track files from Monocle can be used, but I didn't find the relevant guidance in your guidance file😭. How can Monocle result files be used in TraSig?

**Comment by doraadong** [comment]
Hi, thanks for your interest! Please find the Tutorials section in the readme file for more details. Specifically, the most relevant one should be tutorials/Prepare_input_from_user_defined_trajectory.ipynb. Let me know if you still have questions.
