### ISSUE TITLE
Output from main.py cannot be used for analyze_outputs.py 

### ISSUE THREAD

**Issue by ZainulArifin1** [doraadong/TraSig#2]
Hi,

First of all, thank you for the package. I think it's an interesting concept to link pseudotime to increase the robustness of CCI analysis. I tried running trasig using the example dataset and got the following file as an output:
oligodendrocyte-differentiation-clusters_marques_ligand_receptor_ti_slingshot_smallerWindow_nlap_20_3_permutation_results.pickle

When I tried running the analyze_outputs.py it returns an error because it can't locate "oligodendrocyte-differentiation-clusters_marques_ligand_receptor_ti_slingshot_smallerWindow_nlap_20_5_permutation_results.pickle", if I tried changing this output file name to match the one required, the result of my CCI analysis is very different from the one in the tutorial.

![oligodendrocyte-differentiation-clusters_marques_ligand_receptor_ti_slingshot_smallerWindow_nlap_20_5_dot_summary_scores](https://user-images.githubusercontent.com/46014847/191491678-62b67cd9-1aeb-4c03-96d6-c995afae3fbd.png)

**Comment by doraadong** [comment]
Hi, thank you for your interest in our method! It seems you used 1e3 permutations when generate the output( 3 in "..nlap_20_3_permutation.." means using 1e3 permutations). While in our tutorial, we use 1e5 permutations. You can change the number of permutations by using -n 100000 or --numPerms 100000. Let me know if you still have questions.

**Comment by ZainulArifin1** [comment]
Thanks, the tutorial run just fine now. I suppose the higher the permutation number, the more robust the result will be but it will be slower to run, is this correct?

**Comment by doraadong** [comment]
We use permutations to generate the background distribution. The higher the permutation number, the more samples you have to generate the distribution and thus more precise. Yes, it takes longer to generate more permutations.
